const cities = [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas",
    "San Jose", "Austin", "Jacksonville", "San Francisco", "Indianapolis", "Columbus", "Fort Worth", "Charlotte", "Seattle",
    "Denver", "El Paso", "Detroit", "Washington", "Boston", "Memphis", "Nashville", "Portland", "Oklahoma City", "Las Vegas",
    "Baltimore", "Louisville", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Mesa", "Kansas City", "Atlanta",
    "Long Beach", "Colorado Springs", "Raleigh", "Miami", "Oakland", "Minneapolis", "Tulsa", "Cleveland", "Wichita", "Arlington",
    "New Orleans", "Bakersfield", "Tampa", "Honolulu", "Aurora", "Anaheim", "Santa Ana", "St. Louis", "Riverside", "Corpus Christi",
    "Lexington", "Pittsburgh", "Anchorage", "Stockton", "Cincinnati", "St. Paul", "Toledo", "Greensboro", "Newark", "Plano",
    "Henderson", "Lincoln", "Buffalo", "Jersey City", "Chula Vista", "Fort Wayne", "Orlando", "St. Petersburg", "Chandler",
    "Laredo", "Norfolk", "Durham", "Madison", "Lubbock", "Irvine", "Winston-Salem", "Glendale", "Garland", "Hialeah", "Reno",
    "Chesapeake", "Gilbert", "Baton Rouge", "Irving", "Scottsdale", "North Las Vegas", "Fremont", "Boise", "Richmond",
    "San Bernardino", "Birmingham", "Spokane", "Rochester", "Des Moines", "Modesto", "Fayetteville", "Tacoma", "Oxnard",
    "Fontana", "Columbus", "Montgomery", "Moreno Valley", "Shreveport", "Aurora", "Yonkers", "Akron", "Huntington Beach",
    "Little Rock", "Augusta", "Amarillo", "Glendale", "Mobile", "Grand Rapids", "Salt Lake City", "Tallahassee", "Huntsville",
    "Worcester", "Knoxville", "Grand Prairie", "Newport News", "Brownsville", "Santa Clarita", "Overland Park", "Providence",
    "Jackson", "Garden Grove", "Oceanside", "Fort Lauderdale", "Rancho Cucamonga", "Chattanooga", "Tempe", "Cape Coral",
    "Sioux Falls", "Springfield", "Pembroke Pines", "Elk Grove", "Salem", "Lancaster", "Corona", "Eugene", "Palmdale",
    "Salinas", "Pasadena", "Joliet","Vadodara","Kochi", "Chennai", "Hyderabad", "Ahmedabad", "Kolkata", "Bangalore",
    "Mumbai", "Delhi", "Pune", "Jaipur", "Lucknow", "Chandigarh", "Patna", "Bhopal", "Indore", "Agra",
    "Varanasi", "Kanpur", "Nagpur", "Coimbatore", "Surat", "Visakhapatnam", "Thiruvananthapuram", "Guwahati",
    "Bhubaneswar", "Amritsar", "Kota", "Ajmer", "Aligarh", "Srinagar", "Nashik", "Vadodara", "Ludhiana",
    "Faridabad", "Madurai", "Mangalore", "Raipur", "Aurangabad", "Jamshedpur", "Vijayawada", "Ranchi",
    "Cuttack", "Dehradun", "Udaipur", "Jhansi", "Gwalior", "Mathura", "Rourkela", "Siliguri", "Dhanbad",
    "Tiruchirappalli", "Allahabad", "Gorakhpur", "Jalandhar", "Warangal", "Shillong", "Itanagar", "Gangtok",
    "Kohima", "Imphal", "Agartala", "Aizawl", "Kavaratti"
];